### ISSUE TITLE
Release models?

### ISSUE THREAD

**Issue by pjsample** [smiles724/GGNN_Meets_PLM#1]
Thank you for sharing the paper "When Geometric Deep Learning Meets Pretrained Protein Language Models." I really enjoyed reading it and found it to be very informative and interesting.

I was wondering if the models discussed in the paper will be published? It would be great to have access to them for further exploration and experimentation. 

Thanks,
Paul

**Comment by smiles724** [comment]
Hi Paul,

We are delighted to hear that you enjoy our idea and find it helpful. 

I have updated the readme file and given a more detailed description of how to use the code. We believe it is much easier to get started if you want to try it yourself.

As for your question, do you mean the well-trained models like EGNN, GVP-GNN, and Molformer for each task? I believe with our latest instructions, you can train the model conveniently on your own machine (if encounter any problem, please let me know). However, we are still very pleased to publish the trained model checkpoints in the near future if you hope so.

Best
Fang

**Comment by pjsample** [comment]
Thank you, Fang! The updated readme is very helpful.
