### ISSUE TITLE
edge features

### ISSUE THREAD

**Issue by jaminzzz** [smiles724/GGNN_Meets_PLM#2]
Hello, awesome work！You mentioned in the Supplementary Information that “The number of the dimension for edges is 16”, I would like to ask you after constructing the graph (KNN or r-ball), what do the features of this edge refer to? I'm very curious about this because I didn't read anything about it in the article. I look forward to your reply. Best wishes！

**Comment by smiles724** [comment]
Hi, jaminzzz, thanks for your interest in our work and a very close look at our codes. I appreciate it. As for your question, you are correct that most of our selected architectures (backbones) such as EGNN and Molformer do not require edge feature input. However, the design of GVP-GNN has considered the edge information and incorporates the edge features. Please look at Supplementary for details, or you can directly refer to this original paper. 



![image](https://github.com/smiles724/GGNN_Meets_PLM/assets/39299863/8a002046-0b5b-4cad-b249-20cc6f40b125)
![image](https://github.com/smiles724/GGNN_Meets_PLM/assets/39299863/fe44df08-27d2-4e8b-917a-331910138148)

**Comment by jaminzzz** [comment]
Cool, thanks for the detailed reply.

**Comment by smiles724** [comment]
> Cool, thanks for the detailed reply.

You are welcome. Have a happy holiday.
